# Generated by Django 4.2.5 on 2023-09-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutie',
            name='img',
            field=models.ImageField(default=2, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
